name: Jenkins Plugin Build
on:
  push:
    # Publish `master`
    branches:
      - build_test

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Customize the Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "repo.jenkins-ci.org", "url": "https://repo.jenkins-ci.org/public/" }, { "id": "ossrh", "url": "https://oss.sonatype.org/content/repositories/snapshots" }, {"id": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}"}]'
          plugin_repositories: '[{ "id": "repo.jenkins-ci.org", "url": "https://repo.jenkins-ci.org/public/" }]'
          servers: '[{"id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'

      - name: Build with Maven
        run: |
          mvn -B -P github -C -ff -ntp -U -up package
          mvn -B -P github deploy:deploy-file -DrepositoryId=github -DpomFile=pom.xml -Dfile=target/tss-jenkins.hpi

      - name: Upload HPI File
        uses: actions/upload-artifact@v1
        with:
          name: tss-jenkins.hpi
          path: target/tss-jenkins.hpi
